filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

filebeat.inputs:
- type: log
  encoding: utf-8
  paths:
    - /var/lib/docker/containers/*/*.log
  fields:
    document_type: "docker"

processors:
- decode_json_fields:
    fields: ["log"]
    target: ""
    overwrite_keys: true
- add_docker_metadata: ~

# output.logstash:
#   hosts: ["logstash:5044"]

output.elasticsearch:
  hosts: ["elastic:9200"]
  protocol: "http"
  username: "elastic"
  password: "u3WhGyJuRs2YM1QZvZu4"


