version: '3.7'

services:

  filebeat:
    user: root
    image: pensioner/filebeat:7.6.0
    container_name: filebeat
    restart: always
    environment:
      - BEAT_STRICT_PERMS=false
    volumes:
      - ./configs/filebeat-docker/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk
      - backend

networks:
  elk:
    external: true
  backend:
    external: true
