version: "3"

services:
  db:
    image: mariadb:10.5
    hostname: mariadb
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
  mariadb_data:
    driver: local
