version: "3"

services:
  db:
    # https://hub.docker.com/_/redis
    image: redis:5-alpine
    hostname: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
